tx_fuzz_container_image: "{{ default_tooling_images.tx_fuzz }}"
tx_fuzz_container_name: tx_fuzz_txs

tx_fuzz_container_command:
  - spam
  - --no-al
  - --rpc=https://eth:prAP7jyLJoHzbCa@rpc.bootnode-1.{{ network_subdomain }}
  - --sk=6dfe32fdddefef3aa2eef1165b032b408285180a30b4414938f33c754338b587


tx_fuzz_container_networks: "{{ docker_networks_shared }}"
